/**
 * Sealing a secret so it can live in the database.
 *
 * Node runtime only — createCipheriv and hkdfSync do not exist on Edge. No
 * `import "server-only"`, deliberately and for the same reason as its sibling
 * admin/auth.ts: both are pure crypto with no request binding, and both must
 * be importable by a plain `scripts/check-*.ts`, which `server-only` throws
 * inside. The guard that matters is elsewhere — SETTINGS_KEY has no
 * NEXT_PUBLIC_ prefix, so Next will not put it in a browser bundle, and
 * node:crypto fails a client build outright.
 *
 * The studio pastes a Meta Conversions API token into the admin panel. That
 * token is a bearer credential with no expiry: whoever holds it can send
 * events as the studio's pixel. It therefore cannot sit in plaintext in a row
 * that a database dump, a backup or a support export would carry.
 *
 *
 * WHY A SEPARATE ENV VAR AND NOT ADMIN_SESSION_SECRET
 *
 * Deriving this key from ADMIN_SESSION_SECRET was the first idea and it is the
 * wrong one. Rotating that secret today has exactly one consequence — everyone
 * is signed out. It is cheap, it is the correct reflex when a laptop goes
 * missing, and nothing warns you of a second effect. Binding a stored
 * credential's readability to it turns an encouraged, free operation into one
 * that destroys data, performed by someone with no reason to suspect it.
 *
 * There is a second reason. ADMIN_SESSION_SECRET is validated only as
 * "32 characters or more" — a human-chosen phrase. HKDF derives, it does not
 * stretch: a chosen phrase as AES key material can be ground offline from a
 * database dump. SETTINGS_KEY is 32 RANDOM BYTES, generated by
 * `npm run settings:key`, never typed by a person.
 *
 *
 * WHY THE KEY ID IS OUTSIDE THE CIPHERTEXT
 *
 * "Which key wrote this?" must be answerable WITHOUT attempting to decrypt.
 * That single property is what turns a key rotation from a silent outage into
 * a sentence on screen: the panel can say "the saved token was encrypted with
 * a different key, paste it again" instead of showing a connection that
 * quietly never fires. The id is derived with a DIFFERENT HKDF info string
 * from the encryption key, so publishing it leaks nothing about the key.
 */

import crypto from "node:crypto";

/** Non-secret and fixed. An HKDF salt may be constant; the IV supplies the randomness. */
const HKDF_SALT = "kiddo-settings-v1";
const INFO_KEY = "kiddo:settings:v1:aes-256-gcm";
const INFO_ID = "kiddo:settings:v1:key-id";

const VERSION = "v1";
const IV_BYTES = 12; // GCM's canonical length
const TAG_BYTES = 16;

/** The server is missing or misconfigured its key. Not the studio's fault, and not fixable by re-pasting. */
export class SecretKeyError extends Error {
  readonly misconfigured = true;
}

/** The stored record cannot be read. `reason` decides what the panel says. */
export class SecretUnreadable extends Error {
  constructor(readonly reason: "malformed" | "key-changed" | "tampered") {
    super(reason);
    this.name = "SecretUnreadable";
  }
}

let cachedKey: Buffer | null = null;
let cachedId: string | null = null;

function ikm(): Buffer {
  const raw = process.env.SETTINGS_KEY;
  if (!raw) {
    throw new SecretKeyError(
      "SETTINGS_KEY is not set. Generate one with `npm run settings:key` and paste it into the environment."
    );
  }
  let bytes: Buffer;
  try {
    bytes = Buffer.from(raw.trim(), "base64");
  } catch {
    throw new SecretKeyError("SETTINGS_KEY is not valid base64. Regenerate it with `npm run settings:key`.");
  }
  if (bytes.length !== 32) {
    throw new SecretKeyError(
      `SETTINGS_KEY must be base64 of exactly 32 bytes (got ${bytes.length}). Regenerate it with \`npm run settings:key\`.`
    );
  }
  return bytes;
}

function aesKey(): Buffer {
  if (!cachedKey) {
    cachedKey = Buffer.from(crypto.hkdfSync("sha256", ikm(), HKDF_SALT, INFO_KEY, 32));
  }
  return cachedKey;
}

/** Eight hex characters. A public label, derived with its own info string. */
export function currentKeyId(): string {
  if (!cachedId) {
    cachedId = Buffer.from(crypto.hkdfSync("sha256", ikm(), HKDF_SALT, INFO_ID, 4)).toString("hex");
  }
  return cachedId;
}

/**
 * `v1.<keyId>.<base64( iv | tag | ciphertext )>`
 *
 * Dotted and self-describing, like `salt:hash` in admin/auth.ts and
 * `v1.a1.m0.<epoch>` in analytics/consent.ts. Standard base64, not base64url:
 * this goes into a Postgres column, never into a URL.
 *
 * `aad` binds the ciphertext to the field it belongs in. A record lifted out of
 * one column and pasted into another — or into another row — fails to
 * authenticate instead of decrypting into the wrong place.
 */
export function seal(plaintext: string, aad: string): string {
  const iv = crypto.randomBytes(IV_BYTES);
  const cipher = crypto.createCipheriv("aes-256-gcm", aesKey(), iv, { authTagLength: TAG_BYTES });
  cipher.setAAD(Buffer.from(aad, "utf8"));
  const body = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return `${VERSION}.${currentKeyId()}.${Buffer.concat([iv, tag, body]).toString("base64")}`;
}

/** The key id a record was written with, without touching the key. `null` if unparseable. */
export function recordKeyId(record: string): string | null {
  const parts = record.split(".");
  if (parts.length !== 3 || parts[0] !== VERSION) return null;
  return /^[0-9a-f]{8}$/.test(parts[1]) ? parts[1] : null;
}

export function open(record: string, aad: string): string {
  const parts = record.split(".");
  if (parts.length !== 3 || parts[0] !== VERSION || !/^[0-9a-f]{8}$/.test(parts[1])) {
    throw new SecretUnreadable("malformed");
  }

  /*
   * Checked BEFORE any crypto runs. A record written by another key is a
   * different situation from a tampered one, and the panel says different
   * words for each. Attempting decryption first would collapse both into
   * "tampered" and send the studio hunting for an attacker who is not there.
   */
  if (parts[1] !== currentKeyId()) throw new SecretUnreadable("key-changed");

  let raw: Buffer;
  try {
    raw = Buffer.from(parts[2], "base64");
  } catch {
    throw new SecretUnreadable("malformed");
  }
  /*
   * `<`, not `<=`. A record of exactly iv + tag and nothing else is the VALID
   * encoding of an empty plaintext — which is what clearing a saved token
   * produces. The first draft had `<=` here and refused to read its own
   * output; check-crypto caught it on the "empty string round trips" case.
   */
  if (raw.length < IV_BYTES + TAG_BYTES) throw new SecretUnreadable("malformed");

  const iv = raw.subarray(0, IV_BYTES);
  const tag = raw.subarray(IV_BYTES, IV_BYTES + TAG_BYTES);
  const body = raw.subarray(IV_BYTES + TAG_BYTES);

  try {
    const decipher = crypto.createDecipheriv("aes-256-gcm", aesKey(), iv, { authTagLength: TAG_BYTES });
    decipher.setAAD(Buffer.from(aad, "utf8"));
    decipher.setAuthTag(tag);
    return Buffer.concat([decipher.update(body), decipher.final()]).toString("utf8");
  } catch {
    // GCM refused the tag: the ciphertext, the tag or the AAD was altered.
    throw new SecretUnreadable("tampered");
  }
}

/** True when the server holds a usable key. Lets a caller ask without catching. */
export function hasSettingsKey(): boolean {
  try {
    ikm();
    return true;
  } catch {
    return false;
  }
}

/** Tests only — the derived key is memoised per process. */
export function __resetSecretboxForTests(): void {
  cachedKey = null;
  cachedId = null;
}
